### PR TITLE
Added server password option to egg-factorio.json

### PR DESCRIPTION
**Pull request by Raeniri**
# Description

Added the option to set a password to the server in the panel.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [X] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Please also change it to the pterodactyl egg. If you can't then feel free to ask, then I will do it for you.

**Comment by Raeniri** [comment]
> Please also change it to the pterodactyl egg. If you can't then feel free to ask, then I will do it for you.

I think you should do it as i haven't used pterodactyl before. I could just do it in the JSON file and change just those things if that is alright. Then i could also do the same with the ARM version as well. But if it's needed to export them from panel i can't.

**Comment by QuintenQVD0** [comment]
> > Please also change it to the pterodactyl egg. If you can't then feel free to ask, then I will do it for you.
> 
> I think you should do it as i haven't used pterodactyl before. I could just do it in the JSON file and change just those things if that is alright. Then i could also do the same with the ARM version as well. But if it's needed to export them from panel i can't.

Thats fine. Please just leave this open. I will append the needed changes and then merge this.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Comment by brainshead** [comment]
Is this also possible on the https://github.com/pelican-eggs/games-standalone/tree/main/factorio/factorio-modupdate ?

**Pull request merged**
