### PR TITLE
BeamNG / fixed config generation

### PR DESCRIPTION
**Pull request by gOOvER**
# Description
fixed install error on configgeneration
close: #22 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
This looks fine but would a config not existing cause the server not to start?

**Comment by gOOvER** [comment]
> This looks fine but would a config not existing cause the server not to start?

config was never written, because of an little bug

**Comment by QuintenQVD0** [comment]
> > This looks fine but would a config not existing cause the server not to start?
> 
> config was never written, because of an little bug

Yea I see that but that would still not cause the server not to start as in hus screenshot.

**Comment by gOOvER** [comment]
The server dont start without config. Problem was the URL in the config

**Review by QuintenQVD0 — APPROVED** [review]
LGTM

**Pull request merged**
