### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by YelehaUwU**
# Description

Fixed a typo in the server_webport variable.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [X] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Now export them both from a panel and then this can be merged.

**Comment by YelehaUwU** [comment]
[egg-pterodactyl-multi-theft-auto.json](https://github.com/user-attachments/files/16181657/egg-pterodactyl-multi-theft-auto.json)
[egg-multi-theft-auto.json](https://github.com/user-attachments/files/16181666/egg-multi-theft-auto.json)

**Comment by YelehaUwU** [comment]
@QuintenQVD0

**Comment by QuintenQVD0** [comment]
> [egg-pterodactyl-multi-theft-auto.json](https://github.com/user-attachments/files/16181657/egg-pterodactyl-multi-theft-auto.json) [egg-multi-theft-auto.json](https://github.com/user-attachments/files/16181666/egg-multi-theft-auto.json)

You just exported them? What were you thinking, export them and then append the changes to this pr please.

**Review by QuintenQVD0 — APPROVED** [review]

**Pull request merged**
